name: Build and Deploy

# Trigger the workflow on push to the main branch and via manual dispatch.
on:
  push:
    branches:
      - main
  workflow_dispatch:

# Use concurrency to ensure that an in-progress run isn’t cancelled by a new push.
concurrency:
  group: build-deploy
  cancel-in-progress: false

jobs:
  build:
    name: Build Project
    runs-on: ubuntu-latest
    steps:
      # Step 1: Check out the repository
      - name: Checkout Repository
        uses: actions/checkout@v3

      # Step 2: Set up Node.js (modify version if needed)
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'

      # Step 3: Install dependencies
      - name: Install Dependencies
        run: npm install

      # Step 4: Build the project (ensure your package.json has a build script)
      - name: Build Project
        run: npm run build

      # Step 5: Upload build artifacts (adjust the path if your build output folder differs)
      - name: Upload Build Artifacts
        uses: actions/upload-artifact@v3
        with:
          name: build-artifacts
          path: ./build

  deploy:
    name: Deploy to GitHub Pages
    runs-on: ubuntu-latest
    needs: build
    steps:
      # Step 1: Download build artifacts from the build job
      - name: Download Build Artifacts
        uses: actions/download-artifact@v3
        with:
          name: build-artifacts

      # Step 2: Deploy using the peaceiris GitHub Pages action
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          # Set publish_dir to your build output folder
          publish_dir: ./build
